name: Email Step Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003950@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
